language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - flake8 . --exclude=./tests
  - pytest --cov=./
after_success:
  - codecov